version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE_SERVICE_URL: http://database-service:3001
      ADMINID: sef
      # NODE_ENV: ${NODE_ENV}
      # DATABASE_SERVICE_URL: ${DATABASE_SERVICE_URL}
      # ADMINID: ${ADMINID}
    restart: always

  database-service:
    build: ./database-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      NODE_ENV: production
      MONGODB_URI: mongodb+srv://marianirimia027_db_user:3QiVHpOHXIdLtCAl@bookabench.t5jtxhe.mongodb.net/
      DB_NAME: data
      # NODE_ENV: ${NODE_ENV}
      # MONGODB_URI: ${MONGODB_URI}
      # DB_NAME: ${DB_NAME}
    restart: always

  business-service:
    build: ./business-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      NODE_ENV: production
      DATABASE_SERVICE_URL: http://database-service:3001
      AUTH_SERVICE_URL: http://auth-service:3000
      # NODE_ENV: ${NODE_ENV}
      # DATABASE_SERVICE_URL: ${DATABASE_SERVICE_URL}
      # AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    restart: always
