apiVersion: v1
kind: Secret
metadata:
  name: bookabench-secrets
  namespace: bookabench
type: Opaque
stringData:
  MONGODB_URI: "mongodb://root:rootpass123@mongodb:27017/?authSource=admin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: bookabench
data:
  PORT: "3000"
  NODE_ENV: "development"
  DATABASE_SERVICE_URL: "http://database-service:3001"
  ADMINID: "sef"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: bookabench
data:
  PORT: "3001"
  NODE_ENV: "development"
  DB_NAME: "data"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: business-config
  namespace: bookabench
data:
  PORT: "3002"
  NODE_ENV: "development"
  DATABASE_SERVICE_URL: "http://database-service:3001"
  AUTH_SERVICE_URL: "http://auth-service:3000"
  FRONTEND_URL: "http://localhost:8081"
