apiVersion: v1
kind: Service
metadata:
  name: business-service
  namespace: bookabench
spec:
  type: NodePort
  selector:
    app: business-service
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 32002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
  namespace: bookabench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-service
  template:
    metadata:
      labels:
        app: business-service
    spec:
      containers:
        - name: business-service
          image: bookabench-business:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: business-config
