apiVersion: v1
kind: Service
metadata:
  name: business-service
spec:
  type: NodePort
  selector:
    app: business-service
  ports:
    - port: {{ .Values.businessService.port }}
      targetPort: {{ .Values.businessService.port }}
      nodePort: {{ .Values.businessService.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
spec:
  replicas: {{ .Values.businessService.replicas }}
  selector:
    matchLabels:
      app: business-service
  template:
    metadata:
      labels:
        app: business-service
    spec:
      containers:
        - name: business-service
          image: "{{ .Values.businessService.image }}:{{ .Values.businessService.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.businessService.port }}
          envFrom:
            - configMapRef:
                name: business-config
