apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: NodePort
  selector:
    app: database-service
  ports:
    - port: {{ .Values.databaseService.port }}
      targetPort: {{ .Values.databaseService.port }}
      nodePort: {{ .Values.databaseService.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
spec:
  replicas: {{ .Values.databaseService.replicas }}
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
        - name: database-service
          image: "{{ .Values.databaseService.image }}:{{ .Values.databaseService.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.databaseService.port }}
          envFrom:
            - configMapRef:
                name: database-config
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: bookabench-secrets
                  key: MONGODB_URI
